# ==========================================
# Application
# ==========================================
server.port=5000

# ==========================
# Eureka Client
# ==========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true



# ==========================
# Gateway Routes
# ==========================

# User Service
spring.cloud.gateway.server.webflux.routes[0].id=USERSERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**,/auth/**,/api/users/reports/**

# Location Service
spring.cloud.gateway.server.webflux.routes[1].id=LOCATIONSERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://LOCATIONSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/airports/**,/api/cities/**,/api/location/reports/**


# ==========================================
# Actuator
# ==========================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# ==========================================
# Logging
# ==========================================
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty=INFO



security.jwt.expirationTime=3600000
security.jwt.secret=NzExMWRjM2EtMDBkMi00YjYwLTg5YTktNTcxMDNhZmVkODQx


# =========================================================
# Swagger/OpenAPI Routes
# =========================================================

spring.cloud.gateway.server.webflux.routes[5].id=USERSERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[5].uri=lb://USERSERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/swagger/users/v3/api-docs
spring.cloud.gateway.server.webflux.routes[5].filters[0]=RewritePath=/swagger/users/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[6].id=LOCATIONSERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[6].uri=lb://LOCATIONSERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/swagger/locations/v3/api-docs
spring.cloud.gateway.server.webflux.routes[6].filters[0]=RewritePath=/swagger/locations/v3/api-docs,/v3/api-docs


# =========================================================
# Swagger UI
# =========================================================

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/swagger/users/v3/api-docs

springdoc.swagger-ui.urls[1].name=Location Service
springdoc.swagger-ui.urls[2].url=/swagger/locations/v3/api-docs





