# ==========================================
# Application
# ==========================================
server.port=5000

# ==========================
# Eureka Client
# ==========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true



# ==========================
# Gateway Routes
# ==========================

# User Service
spring.cloud.gateway.server.webflux.routes[0].id=USERSERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**,/auth/**,/api/users/reports/**

# Location Service
spring.cloud.gateway.server.webflux.routes[1].id=LOCATIONSERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://LOCATIONSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/airports/**,/api/cities/**,/api/location/reports/**

# Airline Service
spring.cloud.gateway.server.webflux.routes[2].id=AIRLINESERVICE
spring.cloud.gateway.server.webflux.routes[2].uri=lb://AIRLINESERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/airlines/**,/api/aircrafts/**,/api/airline/reports/**

# Flight Service
spring.cloud.gateway.server.webflux.routes[3].id=FLIGHTSERVICE
spring.cloud.gateway.server.webflux.routes[3].uri=lb://FLIGHTSERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/flights/**,/api/flights-instances/**,/api/flights-schedules/**,/api/flight/reports/**

# Booking Service
spring.cloud.gateway.server.webflux.routes[4].id=BOOKINGSERVICE
spring.cloud.gateway.server.webflux.routes[4].uri=lb://BOOKINGSERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/bookings/**,/api/bookings/reports/**

# Payment Service
spring.cloud.gateway.server.webflux.routes[5].id=PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[5].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/payments/**,/api/payments/reports/**

# Fare Service
spring.cloud.gateway.server.webflux.routes[6].id=FARESERVICE
spring.cloud.gateway.server.webflux.routes[6].uri=lb://FARESERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/fares/**,/api/fares/reports/**


# Seat Service
spring.cloud.gateway.server.webflux.routes[7].id=SEATSERVICE
spring.cloud.gateway.server.webflux.routes[7].uri=lb://SEATSERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/seats/**,/api/seats/reports/**




# ==========================================
# Actuator
# ==========================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# ==========================================
# Logging
# ==========================================
logging.level.org.springframework.cloud.gateway=INFO
logging.level.reactor.netty=INFO



# =========================================================
# Swagger/OpenAPI Routes
# =========================================================

spring.cloud.gateway.server.webflux.routes[8].id=USERSERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[8].uri=lb://USERSERVICE
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/swagger/users/v3/api-docs
spring.cloud.gateway.server.webflux.routes[8].filters[0]=RewritePath=/swagger/users/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[9].id=LOCATIONSERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[9].uri=lb://LOCATIONSERVICE
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/swagger/locations/v3/api-docs
spring.cloud.gateway.server.webflux.routes[9].filters[0]=RewritePath=/swagger/locations/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[10].id=AIRLINESERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[10].uri=lb://AIRLINESERVICE
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/swagger/airlines/v3/api-docs
spring.cloud.gateway.server.webflux.routes[10].filters[0]=RewritePath=/swagger/airlines/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[11].id=FLIGHTSERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[11].uri=lb://FLIGHTSERVICE
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/swagger/flights/v3/api-docs
spring.cloud.gateway.server.webflux.routes[11].filters[0]=RewritePath=/swagger/flights/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[12].id=BOOKINGSERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[12].uri=lb://BOOKINGSERVICE
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/swagger/bookings/v3/api-docs
spring.cloud.gateway.server.webflux.routes[12].filters[0]=RewritePath=/swagger/bookings/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[13].id=PAYMENTSERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[13].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/swagger/payments/v3/api-docs
spring.cloud.gateway.server.webflux.routes[13].filters[0]=RewritePath=/swagger/payments/v3/api-docs,/v3/api-docs


spring.cloud.gateway.server.webflux.routes[14].id=FARESERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[14].uri=lb://FARESERVICE
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/swagger/fares/v3/api-docs
spring.cloud.gateway.server.webflux.routes[14].filters[0]=RewritePath=/swagger/fares/v3/api-docs,/v3/api-docs

spring.cloud.gateway.server.webflux.routes[15].id=SEATSERVICE-SWAGGER
spring.cloud.gateway.server.webflux.routes[15].uri=lb://SEATSERVICE
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/swagger/seats/v3/api-docs
spring.cloud.gateway.server.webflux.routes[15].filters[0]=RewritePath=/swagger/seats/v3/api-docs,/v3/api-docs



# =========================================================
# Swagger UI
# =========================================================

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/swagger/users/v3/api-docs

springdoc.swagger-ui.urls[1].name=Location Service
springdoc.swagger-ui.urls[1].url=/swagger/locations/v3/api-docs

springdoc.swagger-ui.urls[2].name=Airline Service
springdoc.swagger-ui.urls[2].url=/swagger/airlines/v3/api-docs

springdoc.swagger-ui.urls[3].name=Flight Service
springdoc.swagger-ui.urls[3].url=/swagger/flights/v3/api-docs

springdoc.swagger-ui.urls[4].name=Booking Service
springdoc.swagger-ui.urls[4].url=/swagger/bookings/v3/api-docs

springdoc.swagger-ui.urls[5].name=Payment Service
springdoc.swagger-ui.urls[5].url=/swagger/payments/v3/api-docs

springdoc.swagger-ui.urls[6].name=Fare Service
springdoc.swagger-ui.urls[6].url=/swagger/fares/v3/api-docs

springdoc.swagger-ui.urls[7].name=Seat Service
springdoc.swagger-ui.urls[7].url=/swagger/seats/v3/api-docs



